'use strict';
// Légende des cartes :
//  '#' mur   ' ' vide (hors bâtiment)   'D' porte fermée
//  Ouvertures sur l'extérieur (par où l'intervention peut entrer, jamais sortir) :
//  'X' porte extérieure   'W' fenêtre (on voit et on tire au travers, on ne la franchit pas à pied)
//  Sols : '.' béton   ',' parquet   ':' carrelage
//  'S' départ du joueur   'E' ennemi (orientation aléatoire)   '^' 'v' '<' '>' ennemi orienté
//  'H' otage
//  Mobilier (bloque le passage, pas la vue) : 'c' caisse   'B' baril   'T' table   'p' plante   'b' lit   'k' bureau
const LEVELS = [
  {
    name: 'Entrepôt',
    siegeBriefing: "Vous tenez l'entrepôt : de grands volumes, peu de cloisons, et des portes qui grincent. L'intervention peut entrer par les deux portes extérieures comme par les fenêtres — surveillez large.",
    briefing: "Un groupe armé s'est retranché dans un entrepôt et retient des otages. Nettoyez le bâtiment pièce par pièce. Les portes fermées bloquent la vue : ouvrez-les (E) et jetez une flash (G) avant d'entrer quand vous doutez. Ne touchez pas les otages.",
    enemyWeapons: ['ak', 'pistol'],
    map: [
      '######W##################W######',
      '#..........#,,,,,,,,,#.........#',
      '#..S.......#,,,,v,,,,#..c......#',
      'X..........D,,TT,,,,,#.........#',
      '#..........#,,TT,,,,,D.........#',
      '#....c.....#,E,,,,,H,#.....B...W',
      '#....cc....######D####.....B...#',
      '#..........#.........#.........#',
      '#####D######....c....####D######',
      '#::::::::::#...cc....#,,,,,,,,,#',
      '#::::::::::#....E....#,,TTT,,,,#',
      '#::::>:::::D..H......#,,TTT,E,,#',
      '#:::::::E::#....c..E.#,,,,,,,,,#',
      '#::::::::::#.........#,,,,H,,,,#',
      '######D#####D#########,,,,,,,,,#',
      '#.....B..............D,,,,,,,,E#',
      '#...................c#,,,,,,,,,#',
      '#..c.................#,,,,,E,,,#',
      '#..cc................#,,,,,,,,,#',
      '################X###############',
    ],
  },
  {
    name: 'Bureaux',
    siegeBriefing: "Un long couloir central dessert tout l'étage : c'est par là qu'ils passeront, mais les fenêtres des bureaux leur ouvrent aussi les flancs. Refermez derrière vous.",
    briefing: "Prise d'otages dans un immeuble de bureaux. Un long couloir central dessert des salles bondées : ne vous exposez pas dans le couloir plus longtemps que nécessaire et utilisez les bureaux comme couvert.",
    enemyWeapons: ['ak', 'ak', 'pistol'],
    map: [
      '##X###############################',
      '#::::::::#,,,,,,,#,,,,,v,#,,,,,,,#',
      '#:S::::::D,,,E,,,D,,k,,,,D,,E,,,,#',
      '#::::::::#,,kk,,,#,,E,,,,#,,kk,H,#',
      '#::::p:::####D########D#####D#####',
      'W::::::::::::::::::::::::::::::::#',
      '#::::::::::::::::::::::::::::::::#',
      '#####D#########D##########D#######',
      '#,,,,,,,#,,,,,,,,,,#,,,,,,,,,,,,,#',
      '#,,E,,,,#,,,,H,,,,,#,,,,,,,,,,,,,W',
      '#,,kk,,,D,,,,,,,,,,D,,,kk,,,,,,,,#',
      '#,H,,,E,#,,,kk,,,,,#,,,kk,,,,,,,,#',
      '#,,,,,,,#,,,,E,,,,,#,,,,,,,,,,,,,#',
      '####D############D########D#######',
      '#,,,,,,,,,,,,,,,#................#',
      'W,,,,,,,,,,,,,,,#.....E....B..E..#',
      '#,,,TT,,,,,,,,,,D.........c......#',
      '#,,,TT,,,,,,,,,,#........H.......#',
      '#,,,,,,,,,,,p,,,#....c...........#',
      '########X#########################',
    ],
  },
  {
    name: 'Villa',
    siegeBriefing: "Trois rangées de pièces en enfilade et beaucoup de portes : l'intervention peut se glisser partout. Tenez les angles, gardez vos otages près de vous.",
    briefing: "Villa fortifiée : trois rangées de pièces en enfilade, beaucoup de portes, beaucoup d'ennemis. Prenez votre temps, une pièce après l'autre, et rechargez avant chaque entrée.",
    enemyWeapons: ['ak', 'ak', 'ak', 'pistol'],
    map: [
      '######W###########W#################',
      '#:S:::::::::.#,,,,,,,,,,#,,,,,,,E,,#',
      'X::::::::::::#,,,,,,,,,,D,,,,bb,,,,#',
      '#:::::p::::::D,,TT,,,,,,#,,,,,E,,,,#',
      '#::::::::::::#,,TT,,,,,,#,,H,,,,,,,#',
      '#######D##########D############D####',
      '#,,,,,,,,#,,,,,,,,,#...............#',
      '#,,,,,,,,#,,,,H,,,,D......E..c.....#',
      'W,,,,,,,,D,,,,,,,,,#...............#',
      '#,,bb,,,,#,,,,,,E,,#.....H.....B...#',
      '#,,,,,,,,#,,,,E,,,,#...............#',
      '####D#############D#########D#######',
      '#::::::::::#,,,,,,,,,,,#,,,,,,,,,,,#',
      '#::::::::::#,,,,^,,,,,,D,,,,,E,,,,,#',
      '#::::::::::D,,,,,,,,,H,#,,,,,,,,,,,#',
      '#:::TT:::::#,,,kk,,,,,,#,,,,,,,H,,,#',
      '#:::TT:::::#,,,,,E,,,,,#,,bb,,,,,E,#',
      '########X###########################',
    ],
  },
];
