'use strict';
// Légende des cartes :
//  '#' mur   ' ' vide (hors bâtiment)   'D' porte fermée
//  Sols : '.' béton   ',' parquet   ':' carrelage
//  'S' départ du joueur   'E' ennemi (orientation aléatoire)   '^' 'v' '<' '>' ennemi orienté
//  'H' otage
//  Mobilier (bloque le passage, pas la vue) : 'c' caisse   'B' baril   'T' table   'p' plante   'b' lit   'k' bureau
const LEVELS = [
  {
    name: 'Entrepôt',
    briefing: "Un groupe armé s'est retranché dans un entrepôt et retient des otages. Nettoyez le bâtiment pièce par pièce. Les portes fermées bloquent la vue : ouvrez-les (E) et jetez une flash (G) avant d'entrer quand vous doutez. Ne touchez pas les otages.",
    enemyWeapons: ['ak', 'pistol'],
    map: [
      '################################',
      '#..........#,,,,,,,,,#.........#',
      '#..S.......#,,,,v,,,,#..c......#',
      '#..........D,,TT,,,,,#....E....#',
      '#..........#,,TT,,,,,D.........#',
      '#....c.....#,,,,,,,,,#.....B...#',
      '#....cc....######D####..H..B...#',
      '#..........#.........#.........#',
      '#####D######....c....####D######',
      '#::::::::::#...cc....#,,,,,,,,,#',
      '#::::::::::#....E....#,,TTT,,,,#',
      '#::::>:::::D.........#,,TTT,E,,#',
      '#::::::::::#....c....#,,,,,,,,,#',
      '#::::::::::#.........#,,,,H,,,,#',
      '######D#####D#########,,,,,,,,,#',
      '#.....B..............D,,,,,,,,,#',
      '#........E..........c#,,,,,,,,,#',
      '#..c.................#,,,,,E,,,#',
      '#..cc................#,,,,,,,,,#',
      '################################',
    ],
  },
  {
    name: 'Bureaux',
    briefing: "Prise d'otages dans un immeuble de bureaux. Un long couloir central dessert des salles bondées : ne vous exposez pas dans le couloir plus longtemps que nécessaire et utilisez les bureaux comme couvert.",
    enemyWeapons: ['ak', 'ak', 'pistol'],
    map: [
      '##################################',
      '#::::::::#,,,,,,,#,,,,,,,#,,,,,,,#',
      '#:S::::::D,,,E,,,D,,k,,,,D,,E,,,,#',
      '#::::::::#,,kk,,,#,,E,,,,#,,kk,,,#',
      '#::::p:::####D########D#####D#####',
      '#::::::::::::::::::::::::::::::H:#',
      '#:::::::::::::::^::::::::::::::::#',
      '#####D#########D##########D#######',
      '#,,,,,,,#,,,,,,,,,,#,,,,,,,,,,,,,#',
      '#,,E,,,,#,,,,H,,,,,#,,,,,,E,,,,,,#',
      '#,,kk,,,D,,,,,,,,,,D,,,kk,,,,,,,,#',
      '#,,,,,,,#,,,kk,,,,,#,,,kk,,,,,,,,#',
      '#,,,,,,,#,,,,E,,,,,#,,,,,,,,,,,,,#',
      '####D############D########D#######',
      '#,,,,,,,,,,,,,,,#................#',
      '#,,,,,,E,,,,,,,,#.....E....B.....#',
      '#,,,TT,,,,,,,,,,D.........c......#',
      '#,,,TT,,,,,,,,,,#........H.......#',
      '#,,,,,,,,,,,p,,,#....c...........#',
      '##################################',
    ],
  },
  {
    name: 'Villa',
    briefing: "Villa fortifiée : trois rangées de pièces en enfilade, beaucoup de portes, beaucoup d'ennemis. Prenez votre temps, une pièce après l'autre, et rechargez avant chaque entrée.",
    enemyWeapons: ['ak', 'ak', 'ak', 'pistol'],
    map: [
      '####################################',
      '#:S:::::::::.#,,,,,,,,,,#,,,,,,,,,,#',
      '#::::::::::::#,,,,E,,,,,D,,,,bb,,,,#',
      '#:::::p::::::D,,TT,,,,,,#,,,,,E,,,,#',
      '#::::::::::::#,,TT,,,,,,#,,,,,,,,,,#',
      '#######D##########D############D####',
      '#,,,,,,,,#,,,,,,,,,#...............#',
      '#,,E,,,,,#,,,,H,,,,D......E..c.....#',
      '#,,,,,,,,D,,,,,,,,,#...............#',
      '#,,bb,,,,#,,,,,,,,,#.....H.....B...#',
      '#,,,,,,,,#,,,,E,,,,#...............#',
      '####D#############D#########D#######',
      '#::::::::::#,,,,,,,,,,,#,,,,,,,,,,,#',
      '#::::E:::::#,,,,^,,,,,,D,,,,,E,,,,,#',
      '#::::::::::D,,,,,,,,,,,#,,,,,,,,,,,#',
      '#:::TT:::::#,,,kk,,,,,,#,,,,,,,H,,,#',
      '#:::TT:::::#,,,,,E,,,,,#,,bb,,,,,,,#',
      '####################################',
    ],
  },
];
